<?xml version="1.0"?>
<package format="2">
  <name>CatModel2_v2_motion</name>
  <version>0.0.1</version>
  <description>The CatModel2_v2_motion package</description>

  <maintainer email="farbod.farshidian@gmail.com">Farbod Farshidian</maintainer>
  <maintainer email="jcarius@ethz.ch">Jan Carius</maintainer>
  <maintainer email="rgrandia@ethz.ch">Ruben Grandia</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ocs2_ros_interfaces</depend>
  <depend>ocs2_robotic_tools</depend>
  <depend>ocs2_switched_model_interface</depend>
  <depend>grid_map_filters_rsl</depend>
  <depend>CatModel2_v2_interface</depend>
  <depend>CatModel2_v2_dummy</depend>

  <export>                               
    <build_type>ament_cmake</build_type>
  </export>

</package>